language: python
python:
  - 3.8
before_install:
  - pip install pylint
  - pip install pytest
  - pip install pep257
  - pip install pycodestyle
install:
  - pip install codecov
script:
  - python setup.py test,
  - pylint hangman,
  - pep257
  - pycodestyle
#after_success:
#  - codecov

# Отправлять уведомления на почту, если сборка упала
notifications:
  email:
    recipients:
      - whitestoic@gmail.com
    on_success: never
    on_failure: always
