language: python
python:
  - 3.8
install:
  - pip install codecov
script:
  - ./setup.py pytest,
  - pylint hangman,
  - pep257
  - pycodestyle
after_success:
  - codecov

# Отправлять уведомления на почту, если сборка упала
notifications:
  email:
    recipients:
      - whitestoic@gmail.com
    on_success: never
    on_failure: always
