language: python
python:
  - 3.8
script:
  - pytest
  - bash <(curl -s https://codecov.io/bash) -t 7409ec4d-3541-4c3b-a3f7-741482306829

# Отправлять уведомления на почту, если сборка упала
notifications:
  email:
    recipients:
      - whitestoic@gmail.com
    on_success: never
    on_failure: always
