language: python
python:
  - 3.8
script:
  - pytest
  - bash <(curl -s https://codecov.io/bash)

# Отправлять уведомления на почту, если сборка упала
notifications:
  email:
    recipients:
      - whitestoic@gmail.com
    on_success: never
    on_failure: always
