language: python
python:
  - 3.8
install:
  - python setup.py -q install
  - pip install codecov
script:
  - python setup.py test,
  - pylint hangman,
  - pep257
  - pycodestyle
#after_success:
#  - codecov

# Отправлять уведомления на почту, если сборка упала
notifications:
  email:
    recipients:
      - whitestoic@gmail.com
    on_success: never
    on_failure: always
